FROM apache/airflow:2.7.3-python3.10

USER root

# Instalar dependencias del sistema necesarias para LightGBM, XGBoost y otras librerías de ML
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libgomp1 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Copiar y instalar requirements
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
